Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

CPPDEFINES = ['WRTNODE2R_VERSION='+rtconfig.R_VERSION]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
