Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
wrtnode2r_board.c
platform.c
spi_bridge.c
""")

CPPPATH = [cwd]

CPPDEFINES = ['BOOTLOADER_wrtnode']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
