import os
Import('rtconfig')
from building import *

objs = []

if GetDepend('RT_USING_MAPLE'):
    cwd = GetCurrentDir()
    list = os.listdir(cwd)
    for item in list:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
